apiVersion: v1 # using `apps/v1` doesn't work here, not entirely sure why
kind: Pod
metadata:
  namespace: udemy
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 3000 # this needs to map to the port that the nginx server listens on inside of the container
